
var mei = [
  { name: '吹くから', point: '-20', img: 'images/result/fukukara.jpg', detail: '枕が倒れる。 ※蝶が立てば無点'},
  { name: 'ほととぎす', point: '0', img: 'images/result/hototogisu.jpg', detail: '扇子が蝶を落とさない。 ※箱面を打てば「こつり」過料1点（蝶が落ちて立てば無点）'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '夏の夜', point: '2', img: 'images/result/natsunoyo.jpg', detail: '扇子と蝶が落ちて倒れ、枕・扇子・蝶の順に並ぶ。'},
  { name: 'これやこの', point: '3', img: 'images/result/koreyakono.jpg', detail: '扇子と蝶が落ちて倒れ、扇子・枕・蝶の順に並ぶ。'},
  { name: '天の原', point: '4', img: 'images/result/amanohara.jpg', detail: '扇子が枕に寄りかかり、蝶は落ちて倒れる。'},
  { name: '風をいたみ', point: '4', img: 'images/result/kazewoitami.jpg', detail: '扇子と蝶が落ちて倒れ、少し重なり合う。'},
  { name: 'もろとも', point: '5', img: 'images/result/morotomo.jpg', detail: '扇子が落ちて倒れ、蝶は枕の上で倒れる。'},
  { name: 'めぐり逢ひ', point: '5', img: 'images/result/meguriahi.jpg', detail: '扇子と蝶が落ちて倒れ、地紙と蝶が重なり合う。'},
  { name: '契りきな', point: '6', img: 'images/result/chigirikina.jpg', detail: '扇子が枕に寄りかかり、蝶は落ちて倒れ、扇子・枕・蝶の順に並ぶ。'},
  { name: 'このたび', point: '7', img: 'images/result/konotabi.jpg', detail: '扇子が落ちて倒れ、蝶は枕にぶら下がる。'},
  { name: 'きりぎりす', point: '7', img: 'images/result/kirigirisu.jpg', detail: '扇子と蝶が落ちて倒れ、骨と蝶が重なり合う。'},
  { name: '秋風', point: '8', img: 'images/result/akikaze.jpg', detail: '扇子が枕に寄りかかり、その扇子の下に蝶が倒れる。'},
  { name: '春の夜', point: '8', img: 'images/result/harunoyo.jpg', detail: '扇子が枕に寄りかかり、蝶は枕の上で倒れる。'},
  { name: '山川', point: '8', img: 'images/result/yamakawa.jpg', detail: '扇子が枕に寄りかかり、その扇子に蝶が寄りかかる。'},
  { name: 'いにしへ', point: '8', img: 'images/result/inishihe.jpg', detail: '扇子と蝶が落ちて倒れ、要と蝶が重なり合う。'},
  { name: '寂しさ', point: '10', img: 'images/result/sabishisa.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: 'わびぬれば', point: '11', img: 'images/result/wabinureba.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: 'わが庵', point: '13', img: 'images/result/wagaiho.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '難波江', point: '15', img: 'images/result/naniwae.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '田子の浦', point: '15', img: 'images/result/tagonoura.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '筑波嶺', point: '18', img: 'images/result/tukubane.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '天つ風', point: '20', img: 'images/result/amatsukaze.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: 'あしびき', point: '30', img: 'images/result/ashibiki.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '小倉山', point: '30', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '世の中は', point: '30', img: 'images/result/ogurayama.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '恋すてふ', point: '35', img: 'images/result/koisutefu.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '由良のと', point: '35', img: 'images/result/yuranoto.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '春すぎて', point: '35', img: 'images/result/harusugite.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '御垣守', point: '50', img: 'images/result/mikakimori.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '大江山', point: '50', img: 'images/result/ooeyama.jpg', detail: '扇子と蝶が落ちて倒れる。'}
];
