
var mei = [
  { name: '吹くから', point: '-20', img: 'images/result/fukukara.jpg', detail: '枕が倒れる。 ※蝶が立てば無点'},
  { name: 'ほととぎす', point: '0', img: 'images/result/hototogisu.jpg', detail: '扇子が蝶を落とさない。 ※箱面を打てば「こつり」過料1点（蝶が落ちて立てば無点）'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '夏の夜', point: '2', img: 'images/result/natsunoyo.jpg', detail: '扇子と蝶が落ちて倒れ、枕・扇子・蝶の順に並ぶ。'},
  { name: 'これやこの', point: '3', img: 'images/result/koreyakono.jpg', detail: '扇子と蝶が落ちて倒れ、扇子・枕・蝶の順に並ぶ。'},
  { name: '天の原', point: '4', img: 'images/result/amanohara.jpg', detail: '扇子が枕に寄りかかり、蝶は落ちて倒れる。'},
  { name: '風をいたみ', point: '4', img: 'images/result/kazewoitami.jpg', detail: '扇子と蝶が落ちて倒れ、少し重なり合う。'},
  { name: 'もろとも', point: '5', img: 'images/result/morotomo.jpg', detail: '扇子が落ちて倒れ、蝶は枕の上で倒れる。'},
  { name: 'めぐり逢ひ', point: '5', img: 'images/result/meguriahi.jpg', detail: '扇子と蝶が落ちて倒れ、地紙と蝶が重なり合う。'},
  { name: '契りきな', point: '6', img: 'images/result/chigirikina.jpg', detail: '扇子が枕に寄りかかり、蝶は落ちて倒れ、扇子・枕・蝶の順に並ぶ。'},
  { name: 'このたび', point: '7', img: 'images/result/konotabi.jpg', detail: '扇子が落ちて倒れ、蝶は枕にぶら下がる。'},
  { name: 'きりぎりす', point: '7', img: 'images/result/kirigirisu.jpg', detail: '扇子と蝶が落ちて倒れ、骨と蝶が重なり合う。'},
  { name: '秋風', point: '8', img: 'images/result/akikaze.jpg', detail: '扇子が枕に寄りかかり、その扇子の下に蝶が倒れる。'},
  { name: '春の夜', point: '8', img: 'images/result/harunoyo.jpg', detail: '扇子が枕に寄りかかり、蝶は枕の上で倒れる。'},
  { name: '山川', point: '8', img: 'images/result/yamakawa.jpg', detail: '山川'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'},
  { name: '瀬を早み', point: '1', img: 'images/result/sewohayami.jpg', detail: '扇子と蝶が落ちて倒れる。'}
];
